spring.application.name=Auction_Platform
server.port=7788

# H2 Database Settings
spring.datasource.url=jdbc:h2:mem:auctiondb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect

# Enable H2 Web Console
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# Hibernate Auto DDL Generation
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
